### ISSUE TITLE
Improve error message for (older?) unsupported versions

### ISSUE THREAD

**Issue by greschd** [pyansys/pydpf-composites#100]
Trying to load a model created with version 20.1, the following error message is shown.

![image](https://user-images.githubusercontent.com/5692808/214016964-0fdd5ee3-2ee9-431d-b338-2a048f7bac1e.png)

I suspect the corresponding `ACPCompositeDefinitions.h5` simply doesn't contain version information; maybe we could improve the error message in that case?

**Comment by roosre** [comment]
PR which improves the error message in the backend was merged today.
